### ISSUE TITLE
Exception at startup when accessing zmq

### ISSUE THREAD

**Issue by phhorrein** [domogik/domoweb#106]
Hi there, 

I encountered after a few upgrade/downgrade/reinstall on Domoweb. I recently reinstalled Domogik and Domoweb, and now Domoweb throws an exception at startup, right after MQ handler start. 
```
[I 161221 17:01:52 Domoweb:143] Start http server on port '40404'
[I 161221 17:01:52 Domoweb:164] Starting MQ Handler
[E 161221 17:02:17 zmqstream:417] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
        callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/dmg/repositories/domogik-mq-1.3/src/domogikmq/pubsub/subscriber.py", line 126, in _on_message
        self.on_message(mid, jsons)
      File "/opt/dmg/repositories/domoweb/domoweb/handlers.py", line 464, in on_message
        Sensor.update(content["sensor_id"], content["timestamp"], content["stored_value"])
      File "/opt/dmg/repositories/domoweb/domoweb/models.py", line 449, in update
        session.add(s)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1598, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
[E 161221 17:02:17 zmqstream:452] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
        self._handle_recv()
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
        callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/dmg/repositories/domogik-mq-1.3/src/domogikmq/pubsub/subscriber.py", line 126, in _on_message
        self.on_message(mid, jsons)
      File "/opt/dmg/repositories/domoweb/domoweb/handlers.py", line 464, in on_message
        Sensor.update(content["sensor_id"], content["timestamp"], content["stored_value"])
      File "/opt/dmg/repositories/domoweb/domoweb/models.py", line 449, in update
        session.add(s)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1598, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
[E 161221 17:02:17 ioloop:612] Exception in callback None
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
        handler_func(fd_obj, events)
      File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
        self._handle_recv()
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
        callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/dmg/repositories/domogik-mq-1.3/src/domogikmq/pubsub/subscriber.py", line 126, in _on_message
        self.on_message(mid, jsons)
      File "/opt/dmg/repositories/domoweb/domoweb/handlers.py", line 464, in on_message
        Sensor.update(content["sensor_id"], content["timestamp"], content["stored_value"])
      File "/opt/dmg/repositories/domoweb/domoweb/models.py", line 449, in update
        session.add(s)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1598, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
```
I upgraded my system (Ubuntu 16.04 for arm64) recently, but I already restarted Domoweb, and it worked. I have tried to reboot the system, but the issue is still there. 

Any idea on how I could fix this ?

**Comment by fritz-smh** [comment]
Can you try reinstalling domoweb after deleting /var/lib/domoweb/ (do a backup of /var/lib/domoweb before to be able to restore if needed) ?

**Comment by jschaeke** [comment]
I've got exactly the same error since I updated today (git pull on develop branch). I've removed var/lib/domoweb; didn't help. Running latest Raspbian Pixel. I reverted to an earlier checkout (95ba68fbc62aa7b9a614119436c2f10984cb9615) that I randomly picked... same problem

https://gist.github.com/jschaeke/0a4cd4f4196fa0f0caff192e65f8fd21

**Comment by jschaeke** [comment]
I just reinstalled domogik-mq and now it starts without that error anymore... however the icons in domoweb remain empty (don't get state).. in log I see things like:
```
[I 161222 23:16:12 handlers:435] WS: Sending message ["widgetinstance-sensors", {"instance_id": "74", "sensors": {}}]
[I 161222 23:16:12 handlers:201] WS: Received message ["widgetinstance-getcommands",{"instance_id":"74","rest_auth":{"username":"admin","password":"123"}}]
[I 161222 23:16:12 handlers:435] WS: Sending message ["widgetinstance-commands", {"instance_id": "74", "commands": {}}]
[I 161222 23:16:12 handlers:201] WS: Received message ["widgetinstance-getdevices",{"instance_id":"74","rest_auth":{"username":"admin","password":"123"}}]
```

**Comment by fritz-smh** [comment]
Not sure to understand (email notifications shows me a message where you told it was working now...)

Can you sum up the current status ?

**Comment by jschaeke** [comment]
I thought for a moment reinstalling domogik-mq solved it, but I overlooked the same error; so I removed the comment. Current status: the error in the log that we described here, domoweb does not reflect state in buttons, nor do they work.

**Comment by fritz-smh** [comment]
Ok, it is more clear now.
The button state issue is related to the error.

**Comment by fritz-smh** [comment]
Can you show the full startup log ?

Can you also do these commands : 
ls -l /var/lib/domogik
cat /etc/default/domoweb

Le problème n'est pas la MQ, mais la base. Quand un message est reçu via la MQ pour un sensor, il est mis en base sqlite côté domoweb et c'est ça qui pète.

Merci,

**Comment by phhorrein** [comment]
I can't show the full startup log, Domoweb does not start anymore. It stays stuck on 
```
[I 161223 09:26:28 Domoweb:111] Running from : /opt/dmg/repositories/domoweb
[I 161223 09:26:28 loaders:23] PACKS: Loading widgets
[I 161223 09:26:29 loaders:155] PACKS: Loading themes
[I 161223 09:26:29 loaders:181] MQ: Loading Datatype
```

Here is the `ls`: 
```
drwxr-xr-x 3 domoweb root     4096 Dec 23 09:26 backgrounds
-rw-r--r-- 1 domoweb root    66560 Dec 23 09:26 db.sqlite
-rw-r--r-- 1 domoweb domoweb  2576 Dec 23 09:26 db.sqlite-journal
```

Here is the `cat`:
```
DOMOWEB_USER=domoweb
DOMOWEB_PATH=/opt/dmg/repositories/domoweb
```

**Comment by jschaeke** [comment]
Error gone; but no functional buttons (domodroid works; domogik looks also ok)
https://gist.github.com/jschaeke/eb943421e630ff3a18c04fc48e5192d4

**Comment by fritz-smh** [comment]
Sorry, I didn't get a lot of time with the holidays to investigate on your issue.

About mqtt/weather, they are both xpl plugins and it seems we have an issue with the xplgw.

Question 1 : @jschaeke @phhorrein is now domoweb starting for both of you ?
Question 2  : have both of you issue with widgets value with no xpl plugins ?

**Comment by jschaeke** [comment]
1: yes on the hotfix branch it is OK for me
2: everything was empty: mqtt, velbus and weather widgets

**Comment by phhorrein** [comment]
Hi,

sorry for the delay, I have not been able to check this these last few days.
1. no, domoweb is not starting. Well, it's starting, but still with this ZMQ error
2. I do not use any such plugin

**Comment by vdomos** [comment]
I update domoweb on develop branch this evening. The last update is before change release to 0.6.
it's seem, it's the same issue.

    $ git pull
    remote: Counting objects: 31, done.
    remote: Total 31 (delta 21), reused 21 (delta 21), pack-reused 10
    Dépaquetage des objets: 100% (31/31), fait.
    Depuis https://github.com/domogik/domoweb
       dcf11af..920311b  develop    -> origin/develop
     * [nouvelle branche] 0.5-hotfix -> origin/0.5-hotfix
    Mise à jour dcf11af..920311b
    Fast-forward
     components/sensor.html            |   6 ++++
     domoweb/loaders.py                |   2 +-
     packs/widgets/c3_charts/info.json |  23 +++++++++++++-
     packs/widgets/c3_charts/step.html | 204 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
     packs/widgets/c3_charts/step.png  | Bin 0 -> 3634 bytes
     5 files changed, 233 insertions(+), 2 deletions(-)
     create mode 100644 packs/widgets/c3_charts/step.html
     create mode 100644 packs/widgets/c3_charts/step.png

domoweb.log when starting domoweb:

    ...
    [I 170112 23:31:39 Domoweb:126] Starting tornado web server
    [I 170112 23:31:39 Domoweb:140] SSL not activated
    [I 170112 23:31:39 Domoweb:143] Start http server on port '40404'
    [I 170112 23:31:39 Domoweb:164] Starting MQ Handler
    [E 170112 23:31:44 zmqstream:410] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/dmg/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 128, in _on_message
        self.on_message(mid, jsons)
      File "/opt/dmg/domoweb.domogik/domoweb/handlers.py", line 464, in on_message
        Sensor.update(content["sensor_id"], content["timestamp"], content["stored_value"])
      File "/opt/dmg/domoweb.domogik/domoweb/models.py", line 449, in update
        session.add(s)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1490, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped

    [E 170112 23:31:44 zmqstream:445] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
        self._handle_recv()
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/dmg/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 128, in _on_message
        self.on_message(mid, jsons)
      File "/opt/dmg/domoweb.domogik/domoweb/handlers.py", line 464, in on_message
        Sensor.update(content["sensor_id"], content["timestamp"], content["stored_value"])
      File "/opt/dmg/domoweb.domogik/domoweb/models.py", line 449, in update
        session.add(s)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1490, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
  
    [E 170112 23:31:44 ioloop:629] Exception in callback None
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
        self._handle_recv()
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/dmg/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 128, in _on_message
        self.on_message(mid, jsons)
      File "/opt/dmg/domoweb.domogik/domoweb/handlers.py", line 464, in on_message
        Sensor.update(content["sensor_id"], content["timestamp"], content["stored_value"])
      File "/opt/dmg/domoweb.domogik/domoweb/models.py", line 449, in update
        session.add(s)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1490, in add
        raise exc.UnmappedInstanceError(instance)
    UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
   [I 170112 23:32:45 web:1946] 304 GET / (192.168.0.5) 20.25ms
   [I 170112 23:32:45 web:1946] 200 GET /components/widget.html (192.168.0.5) 48.59ms
   [I 170112 23:32:45 web:1946] 200 GET /components/datatypes.html (192.168.0.5) 7.23ms
   ...

**Comment by fritz-smh** [comment]
Is this still the case on develop branch ?

**Comment by vdomos** [comment]
Yes, still the same error after a git pull on develop branch.

Domoweb is very slow to start:

    2017-02-03 22:17:54,322 domoweb:INFO Running from : /opt/dmg/domoweb
    ...
    2017-02-03 22:20:19,717 domoweb:INFO Starting MQ Handler
    2017-02-03 22:20:33,917 tornado.general:ERROR Uncaught exception, closing connection.
    Traceback (most recent call last):
    ...
    2017-02-03 22:22:03,947 tornado.access:INFO 200 GET / (192.168.0.5) 8.65ms
   ...

~5mn for the interface to be accessible but not work (widgets remains empty)

**Comment by vdomos** [comment]
After a complete reinstall, there is no longer the problem for me.
Domogik and Domoweb develop works again.

**Comment by phhorrein** [comment]
OK, I am going to try this.

**Comment by phhorrein** [comment]
I reinstalled the develop version, without cleaning up the files before and problem is solved. Thanks a lot, the issue can be closed for me!
