### ISSUE TITLE
Can't configure widget

### ISSUE THREAD

**Issue by tikismoke** [domogik/domoweb#160]
```
 HTTPServerRequest(protocol='http', host='XXXXXX:40404', method='GET', uri='/configuration?action=widget&id=6', version='HTTP/1.1', remote_ip='XXXXX', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': 'XXXX:40404', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://XXXXX:40404/', 'Cookie': 'hashrestpwd="2|1:0|10:1543511272|11:hashrestpwd|4:MTIz|61a0fecb674151dc2773383d48c8c1ee7f76c4d14990027af81d59290599276c"; user="2|1:0|10:1543511272|4:user|8:YWRtaW4=|80696d9a83c697be72808c57dfd519346916b2db92e17e58835e266b9ebbdb53"', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/dmgtest/domoweb/domoweb/handlers.py", line 123, in get
        forms = WidgetInstanceForms(instance=instance)
      File "/opt/dmgtest/domoweb/domoweb/forms.py", line 620, in __init__
        self.styleform = WidgetStyleForm(handler=handler, data=dataOptions, prefix='styleparam_')
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 212, in __call__
        return type.__call__(cls, *args, **kwargs)
      File "/opt/dmgtest/domoweb/domoweb/forms.py", line 64, in __init__
        super(Form, self).__init__(data=data, prefix=prefix, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 278, in __init__
        self.process(formdata, obj, data=data, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 132, in process
        field.process(formdata)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 792, in process
        self.form = self.form_class(formdata=formdata, obj=data, prefix=prefix)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 212, in __call__
        return type.__call__(cls, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 272, in __init__
        super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 52, in __init__
        field = meta.bind_field(self, unbound_field, options)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/meta.py", line 27, in bind_field
        return unbound_field.bind(form=form, **options)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 346, in bind
        return self.field_class(*self.args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 568, in __init__
        super(IntegerField, self).__init__(label, validators, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'render_kw'

```

**Comment by tikismoke** [comment]
And in develop console from browser i get:

> polymer-xhr.html:90 GET http://XXXXXX:40404/configuration?action=widget&id=6 500 (Internal Server Error)

**Comment by Nico0084** [comment]
Thks for report, WTForms dependency should be updated !

**Comment by tikismoke** [comment]
So easy you said :)
