### ISSUE TITLE
Unable to create some sections

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domoweb#42]
2015-09-20 22:40:52,963 tornado.application:ERROR Uncaught exception GET /configuration?action=addsection&id=1 (192.168.
1.10)
HTTPServerRequest(protocol='http', host='192.168.1.50:50002', method='GET', uri='/configuration?action=addsection&id=1',
 version='HTTP/1.1', remote_ip='192.168.1.10', headers={'Accept-Language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3', 'Accep
t-Encoding': 'gzip, deflate', 'Host': '192.168.1.50:50002', 'Accept': 'text/html,application/xhtml+xml,application/xml;q
=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.0', 
'Connection': 'keep-alive', 'Referer': 'http://192.168.1.50:50002/', 'Cookie': 'admin_home_tour=done; i18next=fr', 'Cont
ent-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execut
e
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 63, in get
    self.render('sectionAdd.html')
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0-py2.7-linux-x86_64.egg/tornado/web.py", line 665, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0-py2.7-linux-x86_64.egg/tornado/web.py", line 772, in render_s
tring
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.0-py2.7-linux-x86_64.egg/tornado/template.py", line 278, in gen
erate
    return execute()
  File "sectionAdd_html.generated.py", line 5, in _tt_execute
    if 'SectionBackgroundCSS' in params:  # sectionAdd.html:133
NameError: global name 'params' is not defined

**Comment by fritz-smh** [comment]
Fixed
