### ISSUE TITLE
domogik-mq fails to start in domogik-mq 1.3

### ISSUE THREAD

**Issue by jcdutton** [domogik/domoweb#60]
Ubuntu 14.04.3 LTS
Error messages:

    Starting 0MQ broker ...Traceback (most recent call last):
     File "/usr/local/bin/dmg_broker", line 5, in <module>
    from pkg_resources import load_entry_point
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'Domogik-MQ==1.3' distribution was not found and is required by the application
    An error occured during 0MQ broker startup.`

**Comment by fritz-smh** [comment]
Could you reinstall domogik-mq and try to start it and give us all the output of install and start ?  

And also move the ticket in domogik tracker. 

Thanks,

**Comment by fritz-smh** [comment]
No response, closing

**Comment by jcdutton** [comment]
I was using the git repo. Turns out if I checkout 1.4 it works.
