### ISSUE TITLE
[develop] Auth error

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#73]
After first login on Domoweb : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 59, in post
    status, msg = self.check_permission(self.get_argument("name", None), self.get_argument("password", None))
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 88, in check_permission
    if e.response.code == 401:
AttributeError: 'NoneType' object has no attribute 'code'

**Comment by overload08** [comment]
2016-08-29 21:20:17,040 domoweb:INFO Authentication : checking persmission. User='admin'
2016-08-29 21:20:17,041 domoweb:INFO REST Call : http://admin:123@127.0.0.1:40406/rest/device
2016-08-29 21:20:17,043 tornado.general:WARNING Connect error on fd 32: ECONNREFUSED
2016-08-29 21:20:17,044 tornado.application:ERROR Uncaught exception POST /login (10.0.0.10)
HTTPRequest(protocol='http', host='10.0.101.25:40404', method='POST', uri='/login', version='HTTP/1.1', remote_ip='10.0.0.10', headers={'Origin': 'http://10.0.101.25:40404', 'Content-Length': '23', 'Accept-Language': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate', 'Host': '10.0.101.25:40404', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://10.0.101.25:40404/login', 'Cache-Control': 'max-age=0', 'Cookie': 'i18next=fr-FR; session=.eJxFkMGOgjAURX9l0rWLocLGxIWmYCB5ryF5StqNyQAKr3YmAQ1S47-P42a2d3HPPfchjqehHTuxug63diGOfSNWD_HxJVYCVRpjQA-89UZab2mfaLVPDKd3rXKJVdEZhhnCJgCXsyHsQR68VVkPDBOyi1EaaUI9I5eJJZDGp8tXMmGAu6VNMFXBWhUOCC-2MollNxm-eJSZB1XfNW0-NRUedi82lTNW5dJSneDfjpBdNG2d9eVaPBeiHofT8frj2u9_hZCx3u1jJJcAp7GmPEJOJ6gOHYbGm5BLUE1v6RwZnzlNB4fn9bvuNrbD-47o-QuZ0WCF.CqSRcQ.fWcAVCvCh3jNs7XJXYEZYq-TlkU', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 59, in post
    status, msg = self.check_permission(self.get_argument("name", None), self.get_argument("password", None))
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 88, in check_permission
    if e.response.code == 401:
AttributeError: 'NoneType' object has no attribute 'code'
2016-08-29 21:20:17,047 tornado.access:ERROR 500 POST /login (10.0.0.10) 7.37ms
2016-08-29 21:20:17,159 tornado.access:INFO 200 GET /widget/camera/noname.png?1472498524067 (185.76.192.34) 4.40ms
2016-08-29 21:20:17,962 domoweb:INFO WS: Sending message ["device-stats", {"timestamp": 1472498417, "sensor_id": 45, "device_id": 8, "stored_value": "0"}]
2016-08-29 21:20:17,987 domoweb:INFO WS: Sending message ["device-stats", {"timestamp": 1472498417, "sensor_id": 44, "device_id": 7, "stored_value": "1"}]
2016-08-29 21:20:18,967 domoweb:INFO WS: Sending message ["device-stats", {"timestamp": 1472498418, "sensor_id": 45, "device_id": 8, "stored_value": "0"}]
^CTraceback (most recent call last):
  File "/opt/dmg/domoweb/Domoweb.py", line 124, in <module>
    ioloop.IOLoop.instance().start()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 662, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1586)
  File "zmq/backend/cython/checkrc.pxd", line 11, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1790)

**Comment by fritz-smh** [comment]
2016-08-29 21:20:17,041 domoweb:INFO REST Call : http://admin:123@127.0.0.1:40406/rest/device
2016-08-29 21:20:17,043 tornado.general:WARNING Connect error on fd 32: ECONNREFUSED

Rest/admin coordinates are not ok in domoweb.cfg
Check this configuration

**Comment by overload08** [comment]
I close this issue, domogik doesn't listen to port 40406
