### ISSUE TITLE
[develop] No history

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#74]
With sensorChart widget : 

2016-08-30 18:32:23,734 domoweb:INFO WS: Received message ["sensor-gethistory",{"caller":1824,"id":40,"from":1472488447,"to":1472574847,"interval":"hour","rest_auth":{"username":"admin","password":"123"}}]
2016-08-30 18:32:23,735 domoweb:INFO REST Call : http://admin:123@10.0.101.25:40406/rest/sensorhistory/id/40/from/1472488447/to/1472574847/interval/hour/selector/avg
2016-08-30 18:32:23,745 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 202, in on_message
    data = yield self.WSSensorGetHistory(jsonmessage[1])
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 355, in WSSensorGetHistory
    j = json_decode(response.body)
  File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 93, in json_decode
    return json.loads(to_basestring(value))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

When I go to the rest URL:
{"values": [[2016, 8, 35, 29, 18, 22.717647215899298], [2016, 8, 35, 29, 19, 22.153124928474426], [2016, 8, 35, 29, 20, 21.26666666666667], [2016, 8, 35, 29, 21, 21.243181818181817], [2016, 8, 35, 29, 22, 20.80227272727273], [2016, 8, 35, 29, 23, 20.258490566037736], [2016, 8, 35, 30, 0, 19.23921568627451], [2016, 8, 35, 30, 1, 18.79821428571429], [2016, 8, 35, 30, 2, 18.491379310344822], [2016, 8, 35, 30, 3, 17.26842105263158], [2016, 8, 35, 30, 4, 16.494736842105265], [2016, 8, 35, 30, 5, 16.33333333333334], [2016, 8, 35, 30, 6, 16.11071428571428], [2016, 8, 35, 30, 7, 17.481034482758623], [2016, 8, 35, 30, 8, 22.755932203389825], [2016, 8, 35, 30, 9, 27.05272727272727], [2016, 8, 35, 30, 10, 26.7719298245614], [2016, 8, 35, 30, 11, 25.08113207547169], [2016, 8, 35, 30, 12, 24.27115384615384], [2016, 8, 35, 30, 13, 24.463265306122445], [2016, 8, 35, 30, 14, 25.191666666666663], [2016, 8, 35, 30, 15, 25.877272727272736], [2016, 8, 35, 30, 16, 26.248484848484843], [2016, 8, 35, 30, 17, 26.153571428571432], [2016, 8, 35, 30, 18, 25.77142857142858]], "global_values": {"max": 28.9, "avg": 21.522882096402945, "min": 14.8}}

What's wrong !?

**Comment by overload08** [comment]
Just turn rest_auth to True in domogik.cfg
