### ISSUE TITLE
Problème Sensor history 

### ISSUE THREAD

**Issue by overload08** [domogik/domoweb#95]
Impossible de récupérer l'historique de valeurs pour les graph...

/var/log/domoweb/console.log
```
2016-11-20 09:55:47,685 domoweb:INFO WS: Received message ["sensor-gethistory",{"caller":1654,"id":40,"from":1479549760,"to":1479636160,"interval":"hour","rest_auth":{"username":"admin","password":"123"}}]
2016-11-20 09:55:47,686 domoweb:INFO REST Call : http://admin:123@10.0.101.25:40406/rest/sensorhistory/id/40/from/1479549760/to/1479636160/interval/hour/selector/avg
2016-11-20 09:55:47,696 domoweb:INFO JSON Values : HTTPResponse(_body=None,buffer=<_io.BytesIO object at 0x7f42f45cb9b0>,code=204,effective_url='http://admin:123@10.0.101.25:40406/rest/sensorhistory/id/40/from/1479549760/to/1479636160/interval/hour/selector/avg',error=None,headers={'Content-Length': '0', 'Content-Type': 'application/json', 'Server': 'TornadoServer/4.2'},reason='NO CONTENT',request=<tornado.httpclient.HTTPRequest object at 0x7f42f8afe510>,request_time=0.009246110916137695,time_info={})
2016-11-20 09:55:47,697 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 205, in on_message
    data = yield self.WSSensorGetHistory(jsonmessage[1])
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/opt/dmg/domoweb/domoweb/handlers.py", line 375, in WSSensorGetHistory
    j = json_decode(response.body)
  File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 93, in json_decode
    return json.loads(to_basestring(value))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

```
root@gi-domogik:/opt/dmg/domoweb# curl -isb -H "Accept: application/json" "http://admin:123@10.0.101.25:40406/rest/sensorhistory/id/40/from/1479549760/to/1479636160/interval/hour/selector/avg"
HTTP/1.1 204 NO CONTENT
Content-Length: 0
Content-Type: application/json
Server: TornadoServer/4.2
```

Par contre, lorsque je mets l'URL direct son mon PC, j'ai bien les valeurs...
```
{"values": [[2016, 11, 46, 19, 11, 8.949019607843137], [2016, 11, 46, 19, 12, 9.386000000000001], [2016, 11, 46, 19, 13, 9.558695652173913], [2016, 11, 46, 19, 14, 9.495454545454546], [2016, 11, 46, 19, 15, 9.359999999999998], [2016, 11, 46, 19, 16, 8.11142857142857], [2016, 11, 46, 19, 17, 7.029999999999999], [2016, 11, 46, 19, 18, 7.05263157894737], [2016, 11, 46, 19, 19, 6.875000000000002], [2016, 11, 46, 19, 20, 14.960526315789476], [2016, 11, 46, 19, 21, 6.529166666666666], [2016, 11, 46, 19, 22, 6.67272727272727], [2016, 11, 46, 19, 23, 6.889285714285712], [2016, 11, 46, 20, 0, 6.906060606060605], [2016, 11, 46, 20, 1, 7.516666666666666], [2016, 11, 46, 20, 2, 8.252000000000002], [2016, 11, 46, 20, 3, 8.726923076923079], [2016, 11, 46, 20, 4, 9.411111111111113], [2016, 11, 46, 20, 5, 10.214814814814817], [2016, 11, 46, 20, 6, 10.894871794871797], [2016, 11, 46, 20, 7, 12.580769230769231], [2016, 11, 46, 20, 8, 12.688888888888885], [2016, 11, 46, 20, 9, 13.158064516129036]], "global_values": {"max": 85.0, "avg": 9.223273657289022, "min": 6.4}}
```

**Comment by overload08** [comment]
Personne n'a d'idée ?

**Comment by fritz-smh** [comment]
J'avoue que je sèche...

**Comment by fritz-smh** [comment]
D'autant que je n'ai pas réussi à reproduire...

A moins que... montre voir ton /etc/domoweb.cfg

**Comment by overload08** [comment]
```
sqlite_db = "/var/lib/domoweb/db.sqlite"
port = 40404
log_file_prefix = '/var/log/domoweb/domoweb.log'
debug = True
rest_url = 'http://10.0.101.25:40406/rest'
use_ssl = False
ssl_certificate = 'ssl_cert.pem'
ssl_key = 'ssl_key.pem'
ssl_port = 40405
```

**Comment by overload08** [comment]
Je n'ai toujours pas trouvé...

**Comment by fritz-smh** [comment]
Question indiscrète... ton domogik/domoweb est installé tout seul sur une machine ?
En désespoir de cause on pourrait envisager un debug à distance (mais je comprendrais tout à fait un refus).

**Comment by overload08** [comment]
Oui, je t'envois tout sur irc en privé

**Comment by overload08** [comment]
Résolu 0.5.0-hotfix
